spring:
  profiles:
    active: default
  config:
    import: optional:configserver:http://user:user@localhost:8888
  cloud:
    config:
      retry:
        max-attempts: 30
        max-interval: 60000
      label: order-approval-service